### ISSUE TITLE
مشاهده پست

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#1]
در صفحه اصلی پس از کلیک روی "ادامه مطلب" هر پست به آدرسی مشابه زیر می رود:
http://ajansekar.com/public/ad/2/%D9%81%D9%88%D8%B1%DB%8C-%D9%81%D9%88%D8%B1%DB%8C-%D8%A8%D9%87-%DB%8C%DA%A9-%D9%BE%DB%8C%DA%A9-%D9%85%D9%88%D8%AA%D9%88%D8%B1%DB%8C-%D8%AC%D9%87%D8%AA-%D8%AA%D9%87%DB%8C%D9%87-%D8%BA%D8%B0%D8%A7-%D9%86%DB%8C%D8%A7%D8%B2%D9%85%D9%86%D8%AF%DB%8C%D9%85-%D8%B4%D9%87%D8%B1%DA%A9-%D8%A8%D9%87%D8%B4%D8%AA%DB%8C
و تصویر زیر مشاهده می شود
<img width="1440" alt="screen shot 2016-08-15 at 6 06 52 pm" src="https://cloud.githubusercontent.com/assets/16553961/17665944/11299c5c-6313-11e6-9597-96a239ff3a64.png">

**Comment by rezakho** [comment]
توضیح: فقط وقتی کاربر لاگین نیست خطا میده

**Comment by najafizadeh23** [comment]
یعنی چی ؟ کاربر لاگین نیست خطا میده؟
اگر منظورتون این هست که در پارامترها ست کردید که رایگان نبینند باید به این نحو باشه که یک پیغام متناسب بده که آقا برو تو یا بیا پول بده

**Comment by rezakho** [comment]
!!!
توضیح برای خودم هست مهندس!!!
درست شده الان
