### ISSUE TITLE
فاصله و اچ آر در صفحه آگهی های استخدامی

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#14]
در صفحه ‌"آگهی های استخدامی" خطی در صفحه جا مانده که باعث ایجاد فاصله شده است
<img width="1440" alt="screen shot 2016-08-15 at 7 39 24 pm" src="https://cloud.githubusercontent.com/assets/16553961/17668764/2027e86e-6320-11e6-884d-00e0adba8abc.png">

**Comment by rezakho** [comment]
Done
