### ISSUE TITLE
پدینگ سکشن کانتنت

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#15]
پدینگ پایین
section
با آیدی
content
از ۴۰ به ۰ تغییر یابد

**Comment by rezakho** [comment]
اینطوری که محتوای صفحات میچسبه به منو؟!!!

**Comment by najafizadeh23** [comment]
نه نمی چسبه
قبل : 
<img width="1426" alt="screen shot 2016-08-16 at 12 32 04 am" src="https://cloud.githubusercontent.com/assets/16553961/17677655/0c5d1092-6349-11e6-99d9-512b82201e34.png">
بعد : 
<img width="1427" alt="screen shot 2016-08-16 at 12 32 46 am" src="https://cloud.githubusercontent.com/assets/16553961/17677661/113ce358-6349-11e6-9608-1375dff8adc7.png">

**Comment by rezakho** [comment]
پایینش درسته نمیچسبه
بالاش رو چک کردی؟

**Comment by najafizadeh23** [comment]
دقت کنید من گفتم : 
**پدینگ پایین**
section
با آیدی
content
از ۴۰ به ۰ تغییر یابد

**Comment by rezakho** [comment]
حالا چرا میزنی عزیز دل
Done
