### ISSUE TITLE
پرواز کبوترها!!!

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#19]
نمایش آیکون توییتر در فوتر مشکل دارد و بالاست
قبل
<img width="188" alt="screen shot 2016-08-15 at 8 10 15 pm" src="https://cloud.githubusercontent.com/assets/16553961/17669827/70ed460a-6324-11e6-9231-93b15b40b0d1.png">
بعد
<img width="176" alt="screen shot 2016-08-15 at 8 10 32 pm" src="https://cloud.githubusercontent.com/assets/16553961/17669831/75b86d68-6324-11e6-8bb4-7b19a22674ac.png">

**Comment by rezakho** [comment]
یعنی عنوان ایشو ها کلا یه درم هست خودش

**Comment by najafizadeh23** [comment]
درم؟!
همون درام؟
فکر کنم بیشتر فان
