### ISSUE TITLE
شبکه های اجتماعی موجود

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#20]
شبکه های اجتماعی موجود به ترتیب اهمیت به قرار زیر است
تلگرام
گوگل پلاس
فیس بوک
توییتر
این ترتیب در طراحی از راست به چپ رعایت گردد
در جاهایی مانند فوتر سایت که حالت کلی دارد به صفحات و کانال ما در این شبکه ها هدایت می گردد
در طراحی آیکون شبکه های اجتماعی موجود در فوتر بک گراند این آیکون در آور و فوکوس به سفید تغییر پیدا می کند
در جاهایی مانند نمایش پست که قصد شیر کردن وجود دارد به لینک هایی چون : 
https://telegram.me/share/url?text=Post_title&url=Post_url
هدایت شود

**Comment by rezakho** [comment]
ایکون گرد تلگرام رو فعلا نداریم
بقیه اصلاح شد

**Comment by najafizadeh23** [comment]
لطفا ایشو رو نبندید تا آیکون تلگرام اضافه بشه
همانطور که گفته شد : 
شبکه های اجتماعی موجود به ترتیب اهمیت به قرار زیر است
تلگرام
گوگل پلاس
فیس بوک
توییتر
**این ترتیب در طراحی از راست به چپ رعایت گردد**
که در فوتر عکس این مطلب هست
همچنین این آیکون ها در فوتر لینک نیست، لطفا تبدیل به لینک شود

**Comment by rezakho** [comment]
به چی لینک بشه
شما که لینک اکانت نداده بودید
در تاریخ ۱۷ اوت ۲۰۱۶ ۶:۵۹ ب.ظ، "mohsen najafizadeh" <
notifications@github.com> نوشت:

**Comment by najafizadeh23** [comment]
میدونم به # لینکشون کنید
در طراحی فوتر لینکی نیست
الان آیکون ها تو یک
li
هستن

**Comment by rezakho** [comment]
از اون حرف ها بودها
در تاریخ ۱۷ اوت ۲۰۱۶ ۷:۰۴ ب.ظ، "mohsen najafizadeh" <
notifications@github.com> نوشت:

**Comment by najafizadeh23** [comment]
نه عزیز
گفتم نیام یه لینک اد کنم جاش ویو بهم بریزه

**Comment by rezakho** [comment]
😏
در تاریخ ۱۷ اوت ۲۰۱۶ ۷:۰۷ ب.ظ، "mohsen najafizadeh" <
notifications@github.com> نوشت:

**Comment by najafizadeh23** [comment]
:D

**Comment by rezakho** [comment]
انجام شد
لینک های شبکه اجتماعی فوتر هم به پارامترها افزوده شد

**Comment by najafizadeh23** [comment]
کامنت دوم بنده رو در این تاپیک بخونید
۱. ترتیب
۲. آیکون تلگرام

**Comment by rezakho** [comment]
مشکل چیه الان؟
هم آیکن تلگرام هست
هم ترتیبش درسته
؟؟؟؟
کش مرورگر رو با کنترل + اف ۵ پاک کردید؟

**Comment by najafizadeh23** [comment]
من که گفتم درست شده 
الکی، یادم رفته بود کش رو پاک کنم 😄
