### ISSUE TITLE
آگهی های هر قسمت باید با همان قسمت مرتبط باشد

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#25]
<img width="1379" alt="screen shot 2016-08-16 at 3 23 40 pm" src="https://cloud.githubusercontent.com/assets/16553961/17696789/f1c42ee6-63c5-11e6-9c61-8b18ca3e0ae5.png">
در تصویر بالا مطابق مستندات داریم : 
... یک قسمت آگهی های فوری (کارفرما پول اضافه داده) را نمایش می دهد

<img width="1365" alt="screen shot 2016-08-16 at 3 29 56 pm" src="https://cloud.githubusercontent.com/assets/16553961/17696861/6fdcb550-63c6-11e6-8a3e-8cf02eb7fd1e.png">
در تصویر بالا نیز مطابق مستندات داریم :
... یک قسمت آگهی های دولتی، سراسری و ویژه را نمایش می دهد از ۳۰ تای جدید (آخر) و منقضی 

به همین ترتیب برای سایر سکشن های تکرار شونده

**Comment by rezakho** [comment]
Done
