### ISSUE TITLE
لینک های ادامه مطلب

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#3]
تمامی "ادامه مطلب" های صفحه اصلی به "۲ ساعت پیش" تغییر می کند.
توضیح : "۲ ساعت پیش" میزان زمان گذشته از انتشار آگهی می باشد که مختص هر آگهی است
نحوه تغییر در ایراد #5 قابل مشاهده است

**Comment by rezakho** [comment]
Done
