### ISSUE TITLE
عدم کارکرد کپچا

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#34]
کپچاها کار نمی کنند
تعداد ۵ حرف خوب است

**Comment by rezakho** [comment]
برای مد دولوپ غیرفعال هست
مشکلی نداره
میخواید فعالش میکنیم

**Comment by najafizadeh23** [comment]
بله 
لطفا فعالش کنید

**Comment by rezakho** [comment]
Done

**Comment by najafizadeh23** [comment]
تعداد ۵ حرف خوب است
