### ISSUE TITLE
جایگاه لینک ادامه مطلب در باکس های بزرگ و اسلایدر

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#4]
در اسلایدر صفحه اصلی جایگاهی برای میزان زمان گذشته از انتشار آگهی وجود ندارد
توضیح : ایراد #3 مطالعه شود

در تصویر زیر جایگاه ادامه مطلب کمی به سمت راست و بالا کشیده شود و به دنبال آن متن عنوان هم بالا کشیده شود و متن عنوان پدینگ بیشتری از اطراف بگیرد
<img width="322" alt="screen shot 2016-08-15 at 6 24 44 pm" src="https://cloud.githubusercontent.com/assets/16553961/17666498/aaf65224-6315-11e6-8fa9-56570596487f.png">
تصویر قبل و بعد در زیر مشاهده می شود
<img width="655" alt="screen shot 2016-08-15 at 6 29 22 pm" src="https://cloud.githubusercontent.com/assets/16553961/17666647/5f57d0da-6316-11e6-93e9-2b34e612dae3.png">

**Comment by rezakho** [comment]
Done

**Comment by najafizadeh23** [comment]
۱. در باکس های موجود در تصویر پایین عنوان مورد بحث ۵ پیکسل بالا و ۵ پیکسل به راست کشیده شود
همچنین عنوان بالای آن (عنوان پست) نیز ۵ پیکس به بالا کشیده شود
<img width="604" alt="screen shot 2016-08-17 at 6 23 05 pm" src="https://cloud.githubusercontent.com/assets/16553961/17739035/f063954e-64a8-11e6-8a10-ff1836a5c5ba.png">

۲. در باکس موجود در تصویر پایین عنوان مورد بحث ۵ پیکسل بالا و ۵ پیکسل به راست کشیده شود
همچنین عنوان بالای آن (عنوان پست) نیز ۱۰ پیکس به بالا کشیده شود
<img width="624" alt="screen shot 2016-08-17 at 6 26 26 pm" src="https://cloud.githubusercontent.com/assets/16553961/17739129/4dfe220a-64a9-11e6-9779-500cae464796.png">
