### ISSUE TITLE
جایگاه لینک ادامه مطلب در باکس های کوچک

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#5]
نحوه تغییر مکان و متن "ادامه مطلب" در سایز کوچک پست ها به شکل زیر است

<img width="654" alt="screen shot 2016-08-15 at 6 44 00 pm" src="https://cloud.githubusercontent.com/assets/16553961/17667060/7f254454-6318-11e6-90b1-3dd7c934a7ab.png">
توضیح: جایگاه "۲ ساعت پیش" در همین مکان ثابت است حتی اگر عنوان پست تک خطی باشد

**Comment by rezakho** [comment]
Done

**Comment by najafizadeh23** [comment]
لطفا جایگاه موارد مذکور به شکل زیر تغییر یابد
<img width="602" alt="screen shot 2016-08-17 at 6 17 18 pm" src="https://cloud.githubusercontent.com/assets/16553961/17738873/4e6149f8-64a8-11e6-9d7b-7b905feae666.png">
<img width="1238" alt="screen shot 2016-08-17 at 6 19 13 pm" src="https://cloud.githubusercontent.com/assets/16553961/17738877/51cb91de-64a8-11e6-99dd-f45817cd1979.png">
<img width="328" alt="screen shot 2016-08-17 at 6 30 10 pm" src="https://cloud.githubusercontent.com/assets/16553961/17738968/ae9fe7ca-64a8-11e6-8805-a4c4518a0af8.png">
۱. در باکس های موجود در تصاویر بالا عنوان مورد بحث ۵ پیکسل بالا و ۵ پیکسل به چپ بروند
