### ISSUE TITLE
افکت اسلایدر صفحه اصلی

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#50]
افکت اسلایدر مانند سایت
[msn.com](http://www.msn.com/)
دکمه قبل و بعد
و بالت های مشابه

**Comment by rezakho** [comment]
این مواردی که دقیقا شبیه هست رو حتما من بعد قید کنید
چون کل پروژه شبیه سایت اصلی نیست، تصور ما این بود که هر اسلایدی باشه کافیه
اسلاید اولی همراه با این تغییر 1.5 روزه کاری زمان برد قشنگ
!!!
