### ISSUE TITLE
مشکل در پرداخت کارجو

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#52]
اقدام به پرداخت کردم ولی نرفتم به مرحله ۳
<img width="1440" alt="screen shot 2016-08-29 at 7 20 37 pm" src="https://cloud.githubusercontent.com/assets/16553961/18055641/efc1d320-6e1d-11e6-8892-1a08e4b0a8d0.png">

**Comment by rezakho** [comment]
لعنتی
مشکل از مرچنت بود
درست شد
چک کنید
