### ISSUE TITLE
جایگاه لینک ادامه مطلب در باکس های بزرگ سکشن های تکرار شونده

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#6]
نحوه تغییر جایگاه "۲ ساعت پیش" در باکس های بزرگ پست به شکل زیر است
<img width="1317" alt="screen shot 2016-08-15 at 6 55 26 pm" src="https://cloud.githubusercontent.com/assets/16553961/17667416/16bfface-631a-11e6-9040-0c484c07be43.png">
<img width="1340" alt="screen shot 2016-08-15 at 6 56 01 pm" src="https://cloud.githubusercontent.com/assets/16553961/17667421/18e0da26-631a-11e6-86ca-43f0e17f124c.png">

**Comment by rezakho** [comment]
منظورت زمان انتشار هست؟ نوشتی ادامه مطلب!

**Comment by najafizadeh23** [comment]
بله

**Comment by rezakho** [comment]
Done

**Comment by najafizadeh23** [comment]
لطفا جایگاه موارد مذکور به شکل زیر تغییر یابد
۱. در باکس های موجود در تصاویر پایین عنوان مورد بحث ۵ پیکسل بالا و ۵ پیکسل به چپ بروند

<img width="604" alt="screen shot 2016-08-17 at 6 27 00 pm" src="https://cloud.githubusercontent.com/assets/16553961/17739233/9d3d5c28-64a9-11e6-99f0-2e8a804918fa.png">

<img width="328" alt="screen shot 2016-08-17 at 6 30 10 pm" src="https://cloud.githubusercontent.com/assets/16553961/17738968/ae9fe7ca-64a8-11e6-8805-a4c4518a0af8.png">
