### ISSUE TITLE
ایکون تخیلی جستجوی پیشرفته

### ISSUE THREAD

**Issue by najafizadeh23** [caspeen/aj#9]
<img width="57" alt="screen shot 2016-08-15 at 7 10 27 pm" src="https://cloud.githubusercontent.com/assets/16553961/17668035/cc4e6d88-631c-11e6-9bc1-5ae1ff2106f7.png">
این قسمت به طور کلی حذف گردد و در منوی بالا یک لینک جستجوی پیشرفته قرار گیرد
<img width="1422" alt="screen shot 2016-08-15 at 7 18 19 pm" src="https://cloud.githubusercontent.com/assets/16553961/17668106/19714c02-631d-11e6-918d-296d6536591a.png">

**Comment by rezakho** [comment]
Done
